### PR TITLE
added dynamic music player support

### PR DESCRIPTION
**Pull request by Deathemonic**
This will make the music player in eww dashboard to work with other player not just spotify but mpd, browsers, vlc, and etc.

and added debian install section on readme

### CODE REVIEW

**Comment by janleigh** [comment]
gonna review this tomorrow. currently partying cause of town fiesta.

**Comment by Deathemonic** [comment]
> gonna review this tomorrow. currently partying cause of town fiesta.

have fun sa iyong fiesta baka merong maraming lechon dyan

**Comment by janleigh** [comment]
> have fun sa iyong fiesta baka merong maraming lechon dyan
 pinoy moment

**Comment by janleigh** [comment]
pushed some changes. have fun fixing merge conflicts ;)

**Comment by aishenreemo** [comment]
pakain naman

**Comment by Deathemonic** [comment]
revert to the previous getPlayerStatusText cause it just spit out this error in bash [: -gt: unary operator expected

**Comment by Deathemonic** [comment]
also some weird bug in your lock script it launches the eww lock and i3-lock but it won't cover the desktop with a wallpaper it's just replace my current wallpaper

probably can be fix by setting a lockscreen widget with a scss class that link to a wallpaper

**Review by Deathemonic — COMMENTED** [review]
I think everything should work properly

**Review by Deathemonic — COMMENTED** [review]
Now everything should work

**Review by janleigh — APPROVED** [review]

**Pull request merged**
